name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.13.1"
          cache: "npm"

      - run: npm ci

      - run: npm test

  # The workflow job name
  discord-notifier:
    # Name of the environment
    environment: secrets
    # Run after the test job completes
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sequence of tasks
    steps:
      - name: Discord Notification
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.WEBHOOKS_URL }}
